Add lesson_4 homeworks.
antdolg1/jg_java_1_wednesday_march_2023 pull request #17
Opened 2023-04-17 19:13 UTC by AndrejsMihailicenko

Add lesson_4 level_1, level_2, homeworks. Homeworks in progress.

2023-04-18 14:30 UTC, antdolg1 commented on src/main/java/students/andrej_mihailicenko/lesson_4/level_1/PositiveOrNegative.java
> +                } else if (number > 0) {
No need to add this else if check, as you have only two options you can replace it with else.

2023-04-18 14:35 UTC, antdolg1 commented on src/main/java/students/andrej_mihailicenko/lesson_4/level_1/PositiveOrNegative.java
> +                }
I see what you tried to do here, good job but what will happen if user enters any other symbol ignoring your message? Also I would suggest to replace `!answer.equalsIgnoreCase("y")` with `answer.equalsIgnoreCase("n")` to avoid NOT operator where it is not needed as it adds complexity.

2023-04-18 15:46 UTC, AndrejsMihailicenko commented on src/main/java/students/andrej_mihailicenko/lesson_4/level_1/PositiveOrNegative.java
> +                }
I used chatgpt to fix my code, now user can enter other symbols and programm still works!

2023-04-18 17:58 UTC, antdolg1 commented on src/main/java/students/andrej_mihailicenko/lesson_4/level_1/PositiveOrNegative.java
> +                }
Yeah, I can see that :D 

So I this code still looks strange for me. First of all, you check if user entered "y" or "n" and if he did you break out of inner loop but actually if user enters "y" you have recursion (infinite loop) which is bad. Basically you are trying to overengineer simple task, there are ways how to check if Y on N was entered, using regex and pattern matchers but this is not the topic of this course and lesson. I suggest to simplify the code.

First you don't need inner loop so it can be removed and replaced with:

```
            System.out.println("Continue?(y/n)");
            String answer = scanner.next();

            if (answer.equalsIgnoreCase("n")) {
                break;
            } else if (answer.equalsIgnoreCase("y")) {
                //continue
            } else {
                System.out.println("Invalid input. Please enter 'y' or 'n'.");
            }
```

Then I suggest to move this line `System.out.println("Enter your number: ");` inside while loop so if user decides to check another number it is clear for him that he needs to enter another number.

And third, as we use break; to end or loop there is no need for variable 
```
        boolean continueProgram = true;
        while (continueProgram) {
```

and we can replace it with:
        `while (true) {`
        
        
Let me know if something is not clear.

2023-04-18 17:59 UTC, antdolg1 requested changes
See my comment.

2023-04-18 18:36 UTC, AndrejsMihailicenko commented on src/main/java/students/andrej_mihailicenko/lesson_4/level_1/PositiveOrNegative.java
> +                }
I tried to figure it all out. I rewrite lesson 4 tasks, now user can use programs without restarting them. I know it wasn't required, but I was interested in understanding this cycle.

2023-04-19 09:39 UTC, antdolg1 approved these changes

2023-04-19 09:39 UTC, merged